project_name: MD5Dog
builds:
  - env:
      - CGO_ENABLED=0
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags: "-s -w"
    id: "MD5Dog"
    binary: "MD5Dog"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "v1.1-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
